### ISSUE TITLE
Nulls treated like zeros, skewing chart

### ISSUE THREAD

**Issue by claude2** [etpinard/plotlyjs-finance#3]
If chart data happens to contain 1 or more null points, they will be equated with 0 and the chart will have minX = 0.

Demo: http://jsbin.com/huposonopu/edit?js,output

**Comment by etpinard** [comment]
Hi, this repo is now deprecated.

As of [`v1.18.0`](https://github.com/plotly/plotly.js/releases/tag/v1.18.0), plotly.js now include native 
`ohlc` and `candlestick` trace types. 

See live example: http://codepen.io/etpinard/pen/ZpRPqW
