### ISSUE TITLE
Streaming locally?

### ISSUE THREAD

**Issue by claude2** [etpinard/plotlyjs-finance#4]
What is the best way to stream a chart? Let's say data comes from REST API.

We can just plot the new new chart all the time but that is inefficient.

``` js
const fig = PlotlyFinance.createOHLC({...})
`Plotly.newPlot('chart', fig.data, fig.layout);
```

Something like [extendTraces](http://codepen.io/etpinard/pen/qZzyXp)?

**Comment by etpinard** [comment]
Hi, this repo is now deprecated.

As of [`v1.18.0`](https://github.com/plotly/plotly.js/releases/tag/v1.18.0), plotly.js now include native 
`ohlc` and `candlestick` trace types. 

See live example: http://codepen.io/etpinard/pen/ZpRPqW
